### ISSUE TITLE
append only ?

### ISSUE THREAD

**Issue by benoitc** [mikpe/btree#1]
Hi,

I’m wondering how the implementions behave when you modify a node/leqf. are you creating a new one on eaxh edit? Basically i’m looking on an implementation différent from the one i maintain (https://github.com/benoitc/cbt) .

About append only btrees:
http://www.bzero.se/ldapd/btree.html

**Comment by mikpe** [comment]
If an insert causes a particular B-tree node to change, that node is rewritten as a side-effect of that B-tree insert call (i.e., a write is done with a pre-existing PageId as key and an updated Page as data).  It does not allocate new nodes unless the B-tree needs to grow.

The user-provided I/O callback does the write, and if the backing store is append-only (like LevelDB) the (re)write becomes an append.
